### ISSUE TITLE
SPDF now requires use of FTPS

### ISSUE THREAD

**Issue by captbuckrogers25** [mattkjames7/pyomnidata#2]
SPDF now requires use of FTPS instead of regular FTP (https://spdf.gsfc.nasa.gov/ftps_readme.html) meaning that an attempt to run UpdateLocalData.py will fail in a timed-out connection.

Solution: 
replace line 13 of `Globals.py' with:
ftpadress = 'ftps://spdf.gsfc.nasa.gov/pub/data/omni/high_res_omni/'

(just change ftp:// to ftps://)

Tested on Ubuntu 20.04 running on WSL1 - 2023-05-30

Submitted with apologies for not just issuing a pull request

**Comment by mattkjames7** [comment]
Hi captbuckrogers25,
I'm sorry for the slow response.
Thank you for making me aware of this bug and finding the suitable fix for it!
I have a couple of other fixes to make to this and one or two of its dependencies, so I will add this to my todo list.
Cheers,
Matt.

**Comment by mattkjames7** [comment]
Can I ask what version of pyomnidata you are using? 

I had a quick look at the code and the `ftpadress` variable doesn't seem to be used any more. I replaced the old `wget` based code which used `ftpadress` with `ftplib.FTP_TLS` a while ago in order to make the module compatible with Windows. 

This method seems to be working still, though please let me know if it's not working correctly for you.

Cheers!
